name: Build

on:
  push:
    branches:
      - "main"

env:
  cache-version: v5
  windows-target: x86_64-pc-windows-gnu

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      #- name: Add Cargo to PATH
      #  run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      # - name: Cache Cargo
      #   id: cache-cargo
      #   uses: actions/cache@v4
      #   with:
      #     path: $HOME/.cargo
      #     key: ubuntu-22.04-cache-cargo-${{ env.cache-version }}
      - name: Cache Cargo packages
        id: rust-cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ env.cache-version }}-v2
      - name: Install Rustup
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --target ${{ env.windows-target }}
      - name: Cache Apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: mingw-w64 lld
          version: ${{ env.cache-version }}-v2
      - name: Install Apt packages
        run: sudo apt-get install -y mingw-w64 lld
      - name: Build for Linux
        run: cargo build --release
      - name: Build for Windows
        run: cargo build --target ${{ env.windows-target }} --release
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "release-${{ github.run_id }}-${{ github.run_attempt }}"
          prerelease: false
          title: "Home-Env Bootstrap"
          files: |
            target/release/bootstrap
            target/${{ env.windows-target }}/release/bootstrap.exe