name: Build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Add Cargo to PATH
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      - name: Cache Cargo
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: $HOME/.cargo
          key: ubuntu-22.04-cache-cargo
      - name: Install rustup
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: curl --proto '=https' -y --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --target x86_64-pc-windows-gnu
      - name: Cache Cargo packages
        uses: Swatinem/rust-cache@v2
        with:
          # The prefix cache key, this can be changed to start a new cache manually.
          prefix-key: "v2"
      - name: Cache Apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: mingw-w64
          version: 1.0
      - name: Build for Linux
        run: cargo build --release
      - name: Build for Windows
        run: cargo build --target x86_64-pc-windows-gnu --release
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "release-${{ github.run_id }}-${{ github.run_attempt }}"
          prerelease: false
          title: "Home-Env Bootstrap"
          files: |
            target/release/bootstrap
            target/x86_64-pc-windows-gnu/release/bootstrap.exe